using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace projecteuler
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    class Problem2
    {
        public static void Main()
        {
            long a = 1;
            long b = 2;
            long sum = 0;
            long c = 2;
            while (c <= 4000000)
            {
                if (c % 2 == 0)
                {
                    sum += c;
                }
                c = a + b;
                a = b;
                b = c;
            }
            Console.WriteLine(sum);
            Console.ReadLine();
        }
    }
}
